AWSTemplateFormatVersion: 2010-09-09
 
#1
Parameters:
  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must be development or production  
 
#2
  InstanceType:
    Description: Select the ec2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
 
#3
  KeyName:
    Description: Key name to SSH to VM's.
    Type: AWS::EC2::KeyPair::KeyName
 
#4
  AvailabilityZone:
    Description: select the availability zone
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
 
#5
Conditions:
  CreateEIPForProd: !Equals [!Ref EnvironmentName, prod]
 
#6  
Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02457590d33d576c3
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-VM"
 
#7    
  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Properties:
      InstanceId: !Ref MyVMInstance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      EnvironmentName:
        default: "Select the environment DEV or PROD"