Parameters:
  KeyName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: keypair for ssh
  InstanceType:
    Type: String
    Default: t2.micro
Mappings:
  RegionMap:
    us-east-1:
      AMI: 
Resources: 
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMapping [RegionMap, !Ref "AWS::Region", AMI]
      SecurityGroupIds:
        - !Ref EC2SecurityGroup